import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Toaster } from 'sonner'
import Sidebar from "../components/admin/Sidebar";
import Header from "../components/admin/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body suppressHydrationWarning>  
        <main className="w-full flex h-screen bg-grey"> 
          <Toaster position="top-center " richColors   />
         <Sidebar/> 


          <div className="flex-1 "> 
                <Header/>
               <div className="p-4">
 {children} 
               </div>
               

          </div>
        </main>
             

       
        
          </body>
    </html>
  );
}
